# Generated by Django 3.2 on 2023-05-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20230501_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredients',
            new_name='RecipeIngredient',
        ),
        migrations.RenameModel(
            old_name='RecipeTags',
            new_name='RecipeTag',
        ),
    ]
